### ISSUE TITLE
Invite new member: Missing Link to aspecx App store in email

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#103]
Inviting new members from an Android phone results in missing link to the app store. On an iPhone it's working.

![2017-01-16 21_28_05-lonelyscreen airplay receiver](https://cloud.githubusercontent.com/assets/22747157/21998210/ba625568-dc33-11e6-902e-c57b7a36f561.png)

**Comment by ursmeier-mercatus** [comment]
Can you send me an invitation from android, or forward this mail please.

**Comment by ursmeier-mercatus** [comment]
Seems to be an Android Email Client limit.
From the plugin doc:
window.plugins.socialsharing.shareViaEmail(
  'Message', // can contain HTML tags, but support on Android is rather limited:  http://stackoverflow.com/questions/15136480/how-to-send-html-content-with-image-through-android-default-email-client
  'Subject',

Fix in 1.2.2: Expose link (ugly, but functional)

**Comment by xamplo** [comment]
Works
