### ISSUE TITLE
V1.2.2: Caldendar entry on Android (5.1) not working

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#104]
On the Android device, the calendar entry is not working, although the calendar access rights have been granted during the installation.

![screenshot_2017-01-23-08-13-28](https://cloud.githubusercontent.com/assets/22747157/22195691/88f5c4ae-e149-11e6-881c-f2180b75a640.png)

![screenshot_2017-01-23-08-44-52](https://cloud.githubusercontent.com/assets/22747157/22195697/8ccbac4c-e149-11e6-8235-0b8f1618d76c.png)

![screenshot_2017-01-23-08-44-21](https://cloud.githubusercontent.com/assets/22747157/22195700/8fbb95e8-e149-11e6-9d52-637aaf418d13.png)

**Comment by xamplo** [comment]
This is valid for the group owner as well as for the group member

**Comment by ursmeier-mercatus** [comment]
a) Can you check other dates than Jan-23, since this is not a rating date.
b) Otherwise it might be related to Android 5, can you test an Android 6 Version?
    Edit: works on 5.1.1 in emulator

**Comment by xamplo** [comment]
a) Can you check other dates than Jan-23, since this is not a rating date.
Even in later months not entries have been added
b) Otherwise it might be related to Android 5, can you test an Android 6 Version?
The latest version of my phone is 5.1. Unfortunately the android 6 is not available on my current Huawei phone. 
I will look, how I could get a newer Android version

**Comment by ursmeier-mercatus** [comment]
Probably not related to Android 5.1, since it works on the emulator.
aspecx Settings page, disabled "add to calendar", by any chance?
Entries should be 01-02-2017, 08-02-2017, 15-02-2017

**Comment by xamplo** [comment]
I already switch it of and on, reinstalled the app and updated the OS to the latest version

![screenshot_2017-01-23-20-30-03](https://cloud.githubusercontent.com/assets/22747157/22219406/f2c98f58-e1aa-11e6-8c2e-a1d2479f2fd3.png)

![screenshot_2017-01-23-20-32-54](https://cloud.githubusercontent.com/assets/22747157/22219538/69d81240-e1ab-11e6-8e22-0f51a7fb2265.png)

**Comment by ursmeier-mercatus** [comment]
Which calendar are you using? 

My Android emulator looks like this:
![bildschirmfoto 2017-01-23 um 20 51 28](https://cloud.githubusercontent.com/assets/22747183/22220171/e7ad9864-e1ad-11e6-9a50-0e39b3978758.png)

**Comment by xamplo** [comment]
Attached the screens shown with the installed debug version. The first number was 1.

![screenshot_2017-01-25-18-14-42](https://cloud.githubusercontent.com/assets/22747157/22301799/9ac9f6de-e32c-11e6-8846-7a74ffb90989.png)

![screenshot_2017-01-25-18-15-17](https://cloud.githubusercontent.com/assets/22747157/22301810/a0084dc6-e32c-11e6-9c63-adbc244bdb01.png)


![screenshot_2017-01-25-18-15-31](https://cloud.githubusercontent.com/assets/22747157/22301820/a5bc7f62-e32c-11e6-970f-cabbf5e6e448.png)

![screenshot_2017-01-25-18-15-41](https://cloud.githubusercontent.com/assets/22747157/22301825/ab1034c2-e32c-11e6-9a93-85b3f0955c14.png)

![screenshot_2017-01-25-18-15-49](https://cloud.githubusercontent.com/assets/22747157/22301830/aed6b1c6-e32c-11e6-9b46-65781d5c6c14.png)

But no calender to be added/synched. Even not after I deleted all existing calendars.

![screenshot_2017-01-25-18-16-18](https://cloud.githubusercontent.com/assets/22747157/22301865/c900bf2e-e32c-11e6-96a3-01fbb56276a3.png)

**Comment by xamplo** [comment]
![2017-01-31 08_46_15-](https://cloud.githubusercontent.com/assets/22747157/22456328/00869d6a-e792-11e6-842a-1cc1247b6f56.png)
![2017-01-31 08_46_28-](https://cloud.githubusercontent.com/assets/22747157/22456330/0661ec8a-e792-11e6-8bb0-5ab1fed67843.png)
![2017-01-31 08_46_41-](https://cloud.githubusercontent.com/assets/22747157/22456339/10783300-e792-11e6-9bd8-4f5ab8b28681.png)
![2017-01-31 08_46_59-](https://cloud.githubusercontent.com/assets/22747157/22456341/15483524-e792-11e6-9bc4-7676f9745075.png)

**Comment by xamplo** [comment]
![screenshot_2017-01-31-15-03-27](https://cloud.githubusercontent.com/assets/22747157/22467960/ec600b2a-e7c6-11e6-81e3-dd3660dd30ed.png)

**Comment by xamplo** [comment]
![2017-02-01 07_11_33-](https://cloud.githubusercontent.com/assets/22747157/22496909/0f5589b6-e84e-11e6-8354-a21a867e82fe.png)
![2017-02-01 07_11_48-](https://cloud.githubusercontent.com/assets/22747157/22496910/11ed4e8e-e84e-11e6-8653-479e5a57830b.png)
![2017-02-01 07_12_15-](https://cloud.githubusercontent.com/assets/22747157/22496912/14c5ab74-e84e-11e6-9776-af4896dc0e17.png)
![2017-02-01 07_12_31-](https://cloud.githubusercontent.com/assets/22747157/22496914/1713cfc8-e84e-11e6-9fe1-3f696be7a77c.png)
![2017-02-01 07_12_47-](https://cloud.githubusercontent.com/assets/22747157/22496915/1970073c-e84e-11e6-89f2-1b19072fedbc.png)
![2017-02-01 07_13_01-](https://cloud.githubusercontent.com/assets/22747157/22496917/1bbe27b2-e84e-11e6-8918-db5ee9466b0b.png)

**Comment by xamplo** [comment]
Screenschots taken with the last debug version (31.01)

**Comment by ursmeier-mercatus** [comment]
OK. This confirms that non AOSP Phones do not have have "name" (but a "displayname" as a workaround).
Additionally the calendar gets not created. No idea why. Needs more debugging.

**Comment by urm47** [comment]
Added createEvent (without options) for phones where no aspecx-calendar is found after creation.
Version: 1.2.3

**Comment by xamplo** [comment]
Works fine, even after deactivating and activating again the Rating reminder in the settings
