### ISSUE TITLE
User Request: Option to deactive the group owner to provide rates

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#105]
To provide the requested psychological support to her clients, it's very desired to have the option to deactivate the rating ability of the group owner.
The idea is, that the client act as group owner and invites peers, direct reports and superiors to receive continuous rates about his behavior and his performance. The client shouldn't provide rates about himself. Subsequently the results are analyzed with the psychologist and the client to define improvement measurements.
After implementation of this feature, the psychologist's are able to apply the app for their services.

**Comment by ursmeier-mercatus** [comment]
The group owner can always circumvent all restrictions. In this case he could send himself an invitation to be able to rate the group anyway.
We could make this the default: owner has to invite himself, if he wants to rate the group.
But it should be the majority of all cases - not only one customer - for being the default.

**Comment by xamplo** [comment]
Einverstanden. Danke

Gruss
Edo
