### ISSUE TITLE
User Request: The menus Groups and Manage Groups are confusing

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#106]
It's not that clear what can be done in the menu's Groups and Manage Groups. This leads to extra clicks and changes of menu's.
It could probably help, if "Groups" could be renamed to "View Groups" (suggestion of 2 users).

**Comment by ursmeier-mercatus** [comment]
It is actually more than "view" groups:
- view groups (and details)
- accept / reject open invitations
- view / accept rejected invitations

**Comment by xamplo** [comment]
Let us keep it as it is, until more feedbacks have been gathered.
