### ISSUE TITLE
Proposal Pay per user model - first thoughts

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#110]
Only in case you are willing to work on this challenge

[Vorschlag_aspecx_Pay_Per_User_Modell.pdf](https://github.com/xamplo/aspecx/files/752217/Vorschlag_aspecx_Pay_Per_User_Modell.pdf)

**Comment by ursmeier-mercatus** [comment]
I will look into it.

Reminder only (mail 16.11.2016):
c) Lizenzen
c1) „Indi“ / „Club“ / „Small“ / ….  für Fr. x.- im App Store

c2) „Group“ / „Business“ / … ab 100 Lizenzen. 
App „gratis“, aber es fehlt die „Register“-Page. 
Der Kunde schickt uns ein CSV File mit Emails und wir eröffnen die User (oder der Kunde macht es via Web).
Preis: ? Anzahl User x App Store Preis minus Rabatt
Möglichkeit Workshops zu beziehen

c3) „Enterprise“ / ...
Workshops buchen und App ist inbegriffen (User eröffnen analog Model c2)

**Comment by xamplo** [comment]
Hallo Urs

 

Waren nur so Gedanken für den Zukunft, um den Umsatz «anzukurbeln» und um den Maintenance finanzieren zu können.

 

Gruss
Edo

**Comment by xamplo** [comment]
Will be considered in version 3.0 or goveriq
