### ISSUE TITLE
v1.4.0: Can't connect to the app

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#111]
After successful login, subsequently only the screen to logout appears

![img_3083](https://cloud.githubusercontent.com/assets/22747157/22879870/40dab9c0-f1e0-11e6-8e42-700c4cf77679.PNG)

**Comment by ursmeier-mercatus** [comment]
Slide the menu.
This must be related to 1.4.1 which is already half in 1.4.0
Edit:
Should also not work  in the register page
I will fix it.

**Comment by xamplo** [comment]
works now in 1.4.1
