### ISSUE TITLE
v1.4.1: grant accedd to calendar doesn't activate the Rating reminder automatically 

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#113]
On IOS (Android works fine), the "Add rating Dates to Calendar" option doesn't get activated after granting aspecx having access to the calendar, although also the message "Add rating dates to calendar" suggest to automatically add reminders without additional setting changes.

![img_3087](https://cloud.githubusercontent.com/assets/22747157/22928679/fb02bd2a-f2b7-11e6-8abe-f14ba8724f1f.PNG)
![img_3088](https://cloud.githubusercontent.com/assets/22747157/22928680/fc415700-f2b7-11e6-8ca9-79e8797c0f5f.PNG)

**Comment by ursmeier-mercatus** [comment]
Has the option been deactivated in a previous test? 
De-installing the app, does not de-install the account and settings in firebase.

**Comment by xamplo** [comment]
You're right. With a new user it's working as expected.
