### ISSUE TITLE
v1.4.1: Email is not (/only) changeble (once)

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#114]
Email has been successfully changed from edo.plato@gmail.com to info@gmail.com. Subsequently the login was also successful.
To change the email address again, is not possible, as the "Update Email" button couldn't be activated.
Even to logout and login again and to use another email test.test@teat.com didn't work.
![img_3092](https://cloud.githubusercontent.com/assets/22747157/22934816/a23c7956-f2d0-11e6-94d5-961ed2efe7fb.PNG)
![img_3093](https://cloud.githubusercontent.com/assets/22747157/22934815/a23a06f8-f2d0-11e6-9eb9-eadda1bc8224.PNG)

**Comment by xamplo** [comment]
ID in the database and in firebase level are still the same:
rufQtuEUYRVfbbUTLSGo7a8UuY93 (database)
rufQtuEUYRVfbbUTLSGo7a8UuY93 (firebase)

**Comment by xamplo** [comment]
Very conspicuous is the time the App is checking the new email. This process is not stopping (waited more than 5 minutes).

Even changing emails of users without changed email address, this process is hanging,,,

**Comment by ursmeier-mercatus** [comment]
Not working yet. Wait until 1.4.2
Changing email has some serious implications, that we have to discuss first.

**Comment by xamplo** [comment]
tested successfully
