### ISSUE TITLE
v1.4.1: Request to improve date format 

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#115]
It would be more easier to export date data according the format "yyyy.dd.mm hh:mm"
Excel is not automatically recognizing the current exported date format like 2017-02-14T07:06:52.984Z

**Comment by ursmeier-mercatus** [comment]
This is ISO 8601. Can Excel parse this?

**Comment by ursmeier-mercatus** [comment]
Can we leave out the time completely?
e.g. 16.02.2017

**Comment by xamplo** [comment]
Yes, that’s no issue

**Comment by xamplo** [comment]
Yes, no issue!

**Comment by xamplo** [comment]
Is it possible to export the statistics data according following date format: "dd.mm.yyyy".
Currently the format of exported date data is: m/d/yyyy and generates different formats (m/d/yyyy and mm/dd/yyyy).

![2017-02-20 09_28_47-project-team-digitalisation_20170220 csv - notepad](https://cloud.githubusercontent.com/assets/22747157/23117260/26e19a56-f74f-11e6-9a52-2a18be0a9912.png)

This different of date output (m/d/yyyy and mm/dd/yyyy) causes different interpretations by Excel:
Data as marked red, is shown as 01.06.2016. The other data as 12/30/2016.

![2017-02-20 09_10_08-firebase console](https://cloud.githubusercontent.com/assets/22747157/23117497/4d99dc70-f750-11e6-8fac-198da8b653d9.png)
![2017-02-20 09_11_10-project-team-digitalisation_20170220 csv - excel](https://cloud.githubusercontent.com/assets/22747157/23117505/5278a5a0-f750-11e6-85ec-d555db37ea53.png)

**Comment by ursmeier-mercatus** [comment]
OK. Will change it to fixed format.
The date format currently respects the local settings of the device. 

So, the problem above is that your excel import handles dates without leading 0 (e.g. 1/6/2017) not correctly. In the meantime you can change the device localization settings, that should help.

**Comment by xamplo** [comment]
tested successfully
