### ISSUE TITLE
v1.4.4: Email with leading blanks not accepted to reset password. Frebase issue?

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#117]
I am not that sure if we have discussed this t
![img_3247](https://cloud.githubusercontent.com/assets/22747157/23958498/9a9c6876-09a2-11e7-9db1-7419add925e8.PNG)
opic before. I thought it's a firebase issue. Correct?

**Comment by ursmeier-mercatus** [comment]
Same as #69.
We don't check anything on the password entry currently and just hand it over to Firebase.
So, Firebase returns this message, which is correct, because blanks are not allowed in passwords.

**Comment by xamplo** [comment]
Thanks. I couldn't find the related Issue.
