### ISSUE TITLE
v1.4.4: values with more than 1 digit (or with digits after the comma) not readable in the graphs

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#118]
![img_3246](https://cloud.githubusercontent.com/assets/22747157/23958609/eeb0fe18-09a2-11e7-9640-51c3be72cb00.PNG)

**Comment by ursmeier-mercatus** [comment]
It was always like this, but that doesn't make it any better ;-)
I will look into it again, but probably hard to fix.

**Comment by ursmeier-mercatus** [comment]
1.4.5
## Timeseries
- Added some margin to the right
- Slightly repositioned data labels of 2nd data row (1 label to the right, others to the left).
Avoids most "collisions" but not all. But also looks a bit "funny"

Maybe also a solution to #29

**Comment by xamplo** [comment]
works
