### ISSUE TITLE
v1.4.4: Link in the invitation mail not working probably

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#119]
On iphone and android the link redirects to the aspecx.biz/download site and not to the corresponding App stores anymore.
![img_3248](https://cloud.githubusercontent.com/assets/22747157/23959628/f12435cc-09a5-11e7-9fdf-462d955f3e4f.PNG)

**Comment by ursmeier-mercatus** [comment]
The link is correct. But on the server there is an old version of downloadapp.html
I copied my version again to the server to be tested.

Most probably you have an old version locally on your computer which was recopied when you refreshed the other pages.

**Comment by xamplo** [comment]
hmmm still the same behavior. The link directs on both devices to aspecx.biz/download

**Comment by ursmeier-mercatus** [comment]
Just tested it from my iPhone and it works. Caching on your side?

**Comment by xamplo** [comment]
Yes, you are right! Thanks
