### ISSUE TITLE
Logo aspecx covered by the upper IOS bar 

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#12]
Only on iOS is the aspecx logo partially covered.

![2016-10-20 07_22_47-lonelyscreen airplay receiver](https://cloud.githubusercontent.com/assets/22747157/19547187/2e4f3394-9696-11e6-8d14-ec7454e3f0cc.png)

**Comment by ursmeier-mercatus** [comment]
ionic preview app problem. works with the real app
