### ISSUE TITLE
v1.4.4: What should be the behaviour of a deleted aspect

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#120]
This discussion we had already and still I have my doubts.

A deleted aspect can't be rated anymore. Nevertheless in the dashboards it appears, as agreed on.
Makes this still sense, as a deleted aspect is not relevant anymore and could cause confusion. 
What is the added value of a shown but deleted aspect, especially if the aspect is one of the most negative rated.

What's your opinion?

**Comment by ursmeier-mercatus** [comment]
I think we should show the deleted aspects, if rating exists
a) it is **fact** that it was rated
b) the user who rated it, would not trust the aspecx app if aspects suddenly disappear
c) do not allow the admin to deleted unwished/unwanted (badly rated) aspects

In summary: the aspecx credo **transparency**

**Comment by xamplo** [comment]
Ok, makes sense.
