### ISSUE TITLE
Version1.4.6: Statistics are not attached to and send by email

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#123]
Even not while using gmail nor with the default mail client on Android.

**Comment by ursmeier-mercatus** [comment]
Did it ever work on Android, or is this the first test?

**Comment by ursmeier-mercatus** [comment]
Trying a lucky punch in 1.4.7, does it fix it?

**Comment by xamplo** [comment]
Unfortunately I have overseen to test this on Android. My mistake!
I will test 1.4.7 this evening.

**Comment by ursmeier-mercatus** [comment]
Chances are 51% that it works ;-)

**Comment by xamplo** [comment]
Downloaded and installed the 1.4.7 version.

With the standard client the csv file is now attached. However it's not send. Even to open the file is not possible.

With gmail the message appears that permissions are missing to attache a document to the gmail email

I have done some research how to collect the logfiles on android, but for that I have to install the SDK environment and logcat... hmmm

![screenshot_2017-03-21-19-22-51](https://cloud.githubusercontent.com/assets/22747157/24166494/b5ae09f0-0e73-11e7-89bd-2aab24078ee6.png)

![screenshot_2017-03-21-19-23-43](https://cloud.githubusercontent.com/assets/22747157/24166513/cb469eda-0e73-11e7-9c07-e55e5d463ac7.png)

![screenshot_2017-03-21-19-27-41](https://cloud.githubusercontent.com/assets/22747157/24166514/ce33b470-0e73-11e7-992c-ccca943f7506.png)

**Comment by ursmeier-mercatus** [comment]
OK.
These are 2 different issues:
a) missing file
b) permission

I will do some research on this.

**Comment by xamplo** [comment]
Next messages I git and after these messages the app hang. Even after a restart or with other exports: same behavior. The mail client couldn't have been started.

![screenshot_2017-03-22-05-49-51](https://cloud.githubusercontent.com/assets/22747157/24183598/a26d8ef0-0ec9-11e7-811b-dcac6e5e035f.png)

![screenshot_2017-03-22-05-50-39](https://cloud.githubusercontent.com/assets/22747157/24183602/a66b6efa-0ec9-11e7-8919-23767b6ce1f6.png)

![screenshot_2017-03-22-05-50-49](https://cloud.githubusercontent.com/assets/22747157/24183604/aa01328e-0ec9-11e7-8134-99101a11e595.png)

**Comment by ursmeier-mercatus** [comment]
Danke. 
Verstehe noch nichts….Gmail wird vermutlich sehr schwierig…

**Comment by ursmeier-mercatus** [comment]
Hallo Edo

3 x null kann nicht sein ;-) - es liegt am ionic-viewer, der mit den Plugins nicht umgehen kann.
Ich brauche also den Output von einem richtigen Android-Device

Ich habe auf Google Play eine Version 1.4.71 hochgeladen. Es sollte nur noch 1 Alert-Fenster kommen.
Bitte schicken.

Geht die Nicht-Gmail-Version?

Danke & Gruss,
Urs

**Comment by xamplo** [comment]
Nein, der Standard Client geht noch nicht. Attachement wird angehängt, aber nicht mitgeschickt.

Erster Teil:
![screenshot_2017-03-22-12-02-51](https://cloud.githubusercontent.com/assets/22747157/24194927/251223e2-0ef8-11e7-90c6-2147c0d5cfa0.png)

Zweiter Teil:
![screenshot_2017-03-22-12-02-58](https://cloud.githubusercontent.com/assets/22747157/24194943/3044375a-0ef8-11e7-8819-188d18c3e786.png)

Nur zur Info. Bei einer Neu-Installation werdnen die folgenden Berechtigungen verlangt:

![screenshot_2017-03-22-12-01-49](https://cloud.githubusercontent.com/assets/22747157/24194967/41a503a8-0ef8-11e7-9796-dda4d70cba82.png)

**Comment by ursmeier-mercatus** [comment]
Hallo Edo

Das sieht besser aus als erwartet.

1.4.72 ist auf Play Store. Löst das die Gmail Privilegien?

Danke & Gruss,
Urs

**Comment by xamplo** [comment]
Hat nun mit dem Standard Client als auch mit Gmail funktioniert.

Soll die Funktion nun auch mit anderen Mail Clients funktionieren?

**Comment by ursmeier-mercatus** [comment]
Oh? Oh!

Hmmm, Hmmm. Ja ;-)

**Comment by xamplo** [comment]
Works well now
