### ISSUE TITLE
Information: Uppercase Umlaute not shown in most text fields

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#124]
Umlaute in uppercase are not shown in most text fields (Details, Add aspects, Choose most positive aspect, etc.) on Ios as well as on Android. In edit mode and in the dashboards this is working well.

Currently for me not an issue. Only to keep in our mind if the number of users will explode in German speaking countries :-)

**Comment by xamplo** [comment]
![screenshot_2017-03-29-08-09-11](https://cloud.githubusercontent.com/assets/22747157/24441113/5071a750-1458-11e7-9fc4-88854b397273.png)
![screenshot_2017-03-29-08-09-18](https://cloud.githubusercontent.com/assets/22747157/24441114/50995624-1458-11e7-9815-2574f2c7a42b.png)

**Comment by ursmeier-mercatus** [comment]
It is a "space Problem". The umlauts are there, but not visible because of the margin settings in h2:first-child settings in ionic.
Should be easy to fix, but I leave the ionic default settings for the moment, which is:
[padding] h2:first-child: margin-top: -.3rem;

**Comment by xamplo** [comment]
accepted
