### ISSUE TITLE
The rate of a deleted rater in the current rate iteration is partially seen

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#125]
During the current rating iteration, the rates of a deleted rater, who has applied his rate beforehand, is shown in the general rating charts, but not in the remaining charts anymore.

**Comment by ursmeier-mercatus** [comment]
Cannot reproduce with:
a) Create Group
b) Add aspects
c) Add rater
d) Rater accepts invitation
e) Rater rates
f) Admin deletes rater
g) Stats are there 

Which Group are you looking at?
What are your steps to produce the problem?

**Comment by xamplo** [comment]
My mistake. Sorry.
I was so sure that I rated 3 times the same aspect to test the deletion of a rater. But due to the many renames, apparently I rated once aspect 21 instead of aspect 1.
