### ISSUE TITLE
Result test cases v1.4.8: completed successfully

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#127]
All tests, including tests related to the new features and the excel template, have been successfully completed.
A productive version 1.5 can be released.

[aspecx_test_cases_results_version_1.4.8_20170329.pdf](https://github.com/xamplo/aspecx/files/878421/aspecx_test_cases_results_version_1.4.8_20170329.pdf)

**Comment by ursmeier-mercatus** [comment]
OK. Il will release 1.5.0 over the week-end.
