### ISSUE TITLE
appintern: User Feedback - Change color slightly

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#128]
Based on the overwhelmed feedback of the end users, its is requested to slightly change the color of the interface to RGB 224 72 227.

**Comment by xamplo** [comment]
;-)

**Comment by ursmeier-mercatus** [comment]
Excellent. 
I was already afraid that you lost your sense of humor.

**Comment by xamplo** [comment]
Du hast auch Humer :-)

Perfekt. Die Härzchen und Blümchen können wir gerne in der nächsten Version einbauen. Muss nicht sogort sein...

![2017-04-07 06_54_39-groups](https://cloud.githubusercontent.com/assets/22747157/24786101/20b48f24-1b5f-11e7-9407-47e634d5432e.png)
