### ISSUE TITLE
v1.6.30: badge notification is not properly working on iphone

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#129]
In contrarily to Android the Notification badge is not properly working on iphone. The badge number is not automatically increased or decreased due to due ratings, new invitations or deleted invitations. Only after activating aspecx (if the app is going to be active) the badge number changed.

**Comment by ursmeier-mercatus** [comment]
1.6.30 or 1.6.31?
We must discuss this, I need more infos about what your are doing.
This is almost impossible ;-)

**Comment by xamplo** [comment]
Can we call tomorrow morning (between 10 - 12) or afternoon (14 - 16)?
Here some other printscreens to explain the behavior. The 3rd test today confirmed this bug.

Changing the rate dates doesn't increase the badge number in iphone: 

![edo bezemer_gmail_rating_date_firebase](https://cloud.githubusercontent.com/assets/22747157/26281840/7fbed396-3e03-11e7-97c3-3b6e63bd8693.png)


After changing the rate date in firebase (aspecx app runs in the background):


![img_3484](https://cloud.githubusercontent.com/assets/22747157/26281850/b69032b6-3e03-11e7-8119-3a18cd3257ef.PNG)



After opening the app:


![img_3485](https://cloud.githubusercontent.com/assets/22747157/26281855/d0439022-3e03-11e7-80ca-003eda19ed46.PNG)


![img_3486](https://cloud.githubusercontent.com/assets/22747157/26281857/d2cb625c-3e03-11e7-91f1-9c8ad18bc1f3.PNG)


Not before opening the app, tah badge number has changed


![img_3487](https://cloud.githubusercontent.com/assets/22747157/26281859/e4c18798-3e03-11e7-9710-07facc4785b7.PNG)

**Comment by ursmeier-mercatus** [comment]
OK. I understand now. 
This is why we need Push Notifications.

**Comment by xamplo** [comment]
I think so, too...

**Comment by xamplo** [comment]
This issue can be closed as we are working now on push notifications.
