### ISSUE TITLE
Dashboard selection with selection list to switch fast between dashboards

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#13]
At the top of the dashboard screen a selection list should be built in to switch between dashboards fast and easy

**Comment by ursmeier-mercatus** [comment]
There is now a extra selection page for all groups (menu->dashboard). This is easy and fast.
Good enough?
A selection on top of the dashboard screen will clutter the interface.

**Comment by xamplo** [comment]
Good enough!
