### ISSUE TITLE
v1.6.30: Changing the email address in the settings results in inconsistent account

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#130]
After changing the email address in the settings, re-entering the account settings is not possible anymore.
UID keeps the same: 3Nu8NHHBFCMpoDZyGgyte3Opxt92 
Email Account name in Firebase authentication is not changed
Only the email name in users has changed:
![2017-05-19 22_18_27-aspecx-test realtime database firebase console](https://cloud.githubusercontent.com/assets/22747157/26265372/2bcb7f64-3ce1-11e7-88a3-31e345dc2553.png)

![img_3472](https://cloud.githubusercontent.com/assets/22747157/26265434/67e6e1d2-3ce1-11e7-9065-3f639dfdee2c.PNG)

**Comment by ursmeier-mercatus** [comment]
What are your steps? Cannot reproduce.

**Comment by xamplo** [comment]
The steps are:
1. In the Account settings: change email address (edo.bezemer@gmail.com -> edo.bezemer@gmail.con)
2. Logout from App
3. Login in App
4. Change account settings again -> Fails


Just before I did another test and this one succeeded (edo.plato@gmail.com -> edo@gmail.com):


![2017-05-21 09_07_14-aspecx-test authentication firebase console](https://cloud.githubusercontent.com/assets/22747157/26281896/ed01ee60-3e04-11e7-802e-bb126c7b0fa9.png)

**Comment by xamplo** [comment]
Changing the email from  edo@gmail.com to edo@gmail.con:
works as well now....

edo.bezemer@gmail.com -> edo.bezemer@gmail.con is still inconsistent.

**Comment by ursmeier-mercatus** [comment]
Need to discuss. Cannot reproduce.

**Comment by xamplo** [comment]
Do you have time tomorrow? Today the app's behavior was as designed.

**Comment by xamplo** [comment]
Is working
