### ISSUE TITLE
Creation of new accounts in the aspecx app occasionally results in a warning message

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#132]
During the creation of 20 **new** accounts in the app aspecx itself, after successfully creation and subsequently login, the following message appeared that could confuse the user. The message was shown after the creation of 3 accounts out of 20.

The accounts didn't exist before and no error message appeared when the new email address has been entered.

No related log entry found.

Not tested on Android. 

![account_aspecx](https://user-images.githubusercontent.com/22747157/27321072-3215ab9e-5599-11e7-9b6d-cd161af516b4.png)

**Comment by ursmeier-mercatus** [comment]
Hallo Edo

Müssen wir besprechen. Verstehe ich nicht.
Machst du die Accounts auf dem Hany auf? Im Web wäre einfacher, oder?

Gruss,
Urs

**Comment by ursmeier-mercatus** [comment]
Could happen, if the register button is hit twice very quickly. But this rather unlikely.
Or it is related to
<img width="966" alt="bildschirmfoto 2017-06-20 um 11 23 22" src="https://user-images.githubusercontent.com/22747183/27326125-e73ba40e-55aa-11e7-9ad2-a4ef4d4895a7.png">
But then, the error message would be wrong/make no sense.

Also found, that register didn't wait until the database is written. But it shouldn't be related.
==> double check if the /users node is written correctly for the registrations with the error message.

Summary:
?

**Comment by xamplo** [comment]
Can eb closed, as this behavior occurred in a special situation ("mass" creation of accounts)
