### ISSUE TITLE
1.6.5: The "Add Rating Dates to Calendar" default setting can be set to deactivated 

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#135]
With the pushing notification, the Rating Reminder Settings can be set to deactivated. Notifications is a default settings of apps and the calendar function was a work-around. This prevent the user to be over-informed what could cause irritations.

**Comment by ursmeier-mercatus** [comment]
Can we completely remove the calendar feature?

**Comment by xamplo** [comment]
Yes, that's much better, it increases usability.

**Comment by xamplo** [comment]
Works now
