### ISSUE TITLE
1.6.5: After logout, the notification badge is regularly shown

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#136]
In contrary to iphone, in Android the notification badge is still showing the last number of notifications after logout. 
In some logout cases the badge disappeared, independent on the number of open notifications.

Even after stopping the aspecx app (in the background), the badges didn't disappear.
Also after rebooting the device the last notifications are still shown.

**Comment by ursmeier-mercatus** [comment]
Logout clear the badge. And after logout no push notifications are received anymore.
I think that the OS "remberes" badges between installs. Would not know, what we can do.

**Comment by xamplo** [comment]
Not that important, we can collect the user experiences after releasing

**Comment by xamplo** [comment]
As you already mentioned, this seems a OS and not an app issue
