### ISSUE TITLE
1.6.5. Admin is able to delete his own account and can't be corrected

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#137]
I can't remember that I have tested this feature before.
With no administrator or owner the group can't function properly. 
It was not yet possible to correct this issue directly in the database

So actually a bug.

**Comment by ursmeier-mercatus** [comment]
How do you delete an admin?

**Comment by xamplo** [comment]
Manage Groups - Manage Raters - Raters - Delete Rater
:-)

**Comment by xamplo** [comment]
It could happen by accident

**Comment by ursmeier-mercatus** [comment]
This deletes a **rater**, not the **admin**.
The admin can **_continue to manage_** the group.
I still don't get the point.


NB:
But he cannot not invite himself anymore as a rater, because the current rule is, that a rater can be invited only once. The reason for this is, that an admin should not be able to annoy other people.

**Comment by xamplo** [comment]
That behavior restrict corrections after group owner mistakes. Is there a work-arround to be able to fix this issue?

**Comment by ursmeier-mercatus** [comment]
Do you mean, what to do, when the admin confirms deleting a rater after the message 
"Deleting a rater **_cannot be undone_**. Please confirm."
?
;-)

delete /group/raters/<groupid><uid>

**Comment by xamplo** [comment]
That could help yes. Is there no possibility to correct it directly in the database in case the admin deleted a rates by accident and he needs support to get it corrected?

**Comment by ursmeier-mercatus** [comment]
We once also had the requirement, that admins are not allowed to rate.
Now, this is just the opposite.

Need to discuss this issue.

**Comment by xamplo** [comment]
Has been registered as request: #144
