### ISSUE TITLE
1.6.5: Notification badge not always changing

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#138]
Use case:
1. App runs in bacground
2. Change date in the database manually to trigger a rate notification
3. Sometimes the notification badge changed, only after the app has just been activated (app in foreground).
4. Run job https://us-central1-aspecx-79b5a.cloudfunctions.net/onCronBadgeNotification?key=aspecx-test
5. onCronBadgeNotification not always increasing
![2017-06-26 14_29_51-aspecx-test functions firebase console](https://user-images.githubusercontent.com/22747157/27539249-10b3e88e-5a7c-11e7-894d-5daaeb57dc29.png)
6. notification badge not changing unless the app is activated again

I have noticed that in some case the attribute pushed has been added to a rating date:
![2017-06-26 14_35_39-aspecx-test realtime database firebase console](https://user-images.githubusercontent.com/22747157/27539526-2441a6f6-5a7d-11e7-950e-d5c5580f0d67.png)

**Comment by xamplo** [comment]
Just before it was working correctly.
1. changed the rating date to 26.06 (today)
2. Run the cron job
3. Push notification received and a new attribute added.

![2017-06-26 14_53_10-aspecx-test realtime database firebase console](https://user-images.githubusercontent.com/22747157/27540109-3cd53348-5a7f-11e7-9966-8a6b566b27e7.png)

I get the impression, that the sometimes function and sometimes not.

**Comment by ursmeier-mercatus** [comment]
According to the logs, the messages are sent. However, I see some (successful) job executions with no notifications.
Did you change an "open_date" to today before starting the job?

The "pushed" attribute is set, when the message is sent.

**Comment by xamplo** [comment]
Yes, I did.

**Comment by ursmeier-mercatus** [comment]
OK. 
If there isn't any error message in the log, if will be difficult to find the problem.
Any chance to reproduce it?

**Comment by xamplo** [comment]
On Android it works as designed. 
On iphone I have to wait the next day, as the notification badge changes directly after I update the openDate value in the database. So no chance to test the cronjob.

**Comment by ursmeier-mercatus** [comment]
You can kill the app to test, or wait a bit until iOS disconnects the app from the web socket

**Comment by xamplo** [comment]
Killing the app and subsequently running the crontab job I tested already; no change of the badge notification. So I will do the test after a wait period

**Comment by ursmeier-mercatus** [comment]
Just tested iOS. Works for me.

**Comment by xamplo** [comment]
Even if you change the rate date in the database without running the badge, as changing the dates directly in the database the notification badge automatically changes. 
I just changed the date to tomorrow and will observe whether the badge number has increased tomorrow morning after running the badge manually

**Comment by xamplo** [comment]
This morning it worked on ios. Tomorrow I will kill the app without logging out and repeat the test case

**Comment by ursmeier-mercatus** [comment]
Killing the app:
- Double tap the iPhone button
- Swipe the app direction top

A killed app cannot do anything. Then you are able to test anything without waiting for tomorrow.

**Comment by xamplo** [comment]
I did already, The user was not logged out after I activated the app again. This behavior is identical on Android (Swipe up and the app disappears as background app.
Tomorrow morning I will run the crontab and will observe whats going on.

**Comment by xamplo** [comment]
As you already mentioned, the notification badge didn't increase while the app was not running in the background. After starting the app, the badges increase.
I run the crontab twice. Why are there 2 identical entries in the function logfile? The last should find any entry in the database, as the first job did already the work.
The notifcition badge increases by 1, as expected.

**Comment by ursmeier-mercatus** [comment]
We have several issues:
a) Logout
Badge should be set to zero. Does not work on iOS --> Bug

b) App in background or killed
Badge should increase. 
Works for me. Doesn't work for you.
**So we must find out, what we are doing differently.**
According to the log of this morning, you received a Badge of
1 for edo.bezemer@gmail.com on iOS
1 for edo.bezemer@xamplo.com on Android

## Killed vs. in Background
If the data changes, e.g. open_date gets in the current date range
on my Devices  I have the following behavior **_without_** running the CronJob

a) Background
* app not visible
* app **does** appear in the list of active apps
* still logged-in in aspecx

Badge changes on Android for a while (probably until Android needs its resources)
Badge never changes on iOS --> CronJob needs to be executed

b) Killed 
* app **not** visible of course
* does **_not_** appear in the list of active apps
* still logged-in in aspecx

For both Android and iOS Batch-Job/CronJob needs to be executed in order to change the badge

## CronJob:
If an "`open_date === today`" then 

the badeCount (invitations + open_ratings) is calculated and a notification is sent to the user for **_all_** of its devices. 

If you start the badge job 10x, all concerned users receive 10x a notification. 
This is why it will be OK to run the cronJob once a day.

**Comment by ursmeier-mercatus** [comment]
I also tested the "long-running" version. 
Changing open_date for tomorrow, kill app, run CronJob the next day.
Works for me.

**Comment by xamplo** [comment]
Test case (preparation today: 18.07.2017) for 19.07.2017:

- Apple device: for the user edo.bezemer@xamplo.com (YVzvZIV0BrhNzZrFIRh7ZRDTEUX2) I changed the OpenDate (KnUw8ekM6xn9HEcgmOg) to 19.07.2017

- Android device: for the user edo.bezemer@gmail.com (Vw5K12NvuegG8OX3iIKcrdCuzID2) I changed the OpenDate (KnKSHUENAg93QusfyaG) to 19.07.2017

- On apple and android the app will be killed

- Tomorrow morning I will run the cronjob and monitor the badge increase

**Comment by xamplo** [comment]
Result on both devices: negative. 

The badge notification didn't change, although the logfiles show that the notifications have been sent. 

What the reason is, that it works on your device, is interesting to know now.

**Comment by ursmeier-mercatus** [comment]
Changed open_date to 2017-07-20 for
YVzvZIV0BrhNzZrFIRh7ZRDTEUX2/-KnKOzLKfX2tdJ_dS6Hp

I will run the batch tomorrow

**Comment by xamplo** [comment]
Ok, I have killed the app (iphone) and will start the app on your request

**Comment by xamplo** [comment]
Prepared the db for the test during our call:
Changed open_date to 2017-07-21 for
YVzvZIV0BrhNzZrFIRh7ZRDTEUX2 (iphone)
Vw5K12NvuegG8OX3iIKcrdCuzID2 (android)

users are logged out and the app on both devices killed

**Comment by xamplo** [comment]
This morning the test on my iphone was successfully. I tested it (short-running) just before on ipad and it worked.
Tomorrow morning i will do a long-running test on ipad and on 2 iphones

**Comment by ursmeier-mercatus** [comment]
Do you know, what you are doing differently?

**Comment by xamplo** [comment]
In compare to the last test, i had in addition G3 connection. But last month I had wifi and G3/4 and the test failed.

**Comment by xamplo** [comment]
On all iphones (iphone 6 and iphone 5) the long-running test was working. the Ipad not. On the ipad the short-running worked (same account as on iphone, app killed and sibylle.schibli@gmail.com was logged on). 

Tomorrow morning I will redo the test on the ipad (killed app) and on iphone (not killed app)

**Comment by ursmeier-mercatus** [comment]
Hmmm, still don't have a clue..... So far, I never had one single failure.


**I added a new  "body" field  to the message.**

Maybe this will change the behavior of the client device.

You should now also see a "notification tray", if the message gets delivered and the app is killed or in the background.

If no success, I will next change the priority of the message explicitly.

**Comment by xamplo** [comment]
This worked for sibylle. She got 2 message with the text "New aspecx tasks". 

![new_tasks](https://user-images.githubusercontent.com/22747157/28501153-4a7ad3a6-6fd6-11e7-8978-ea064ac91117.jpg)

![2017-07-23 18_37_46-aspecx-test functions firebase console](https://user-images.githubusercontent.com/22747157/28501155-50191502-6fd6-11e7-84a4-569d0363fe55.png)

**Comment by ursmeier-mercatus** [comment]
Vermutlich meine Tests.
Schaue mal morgen, wie es aussieht.


Freundliche Grüsse,

mercatus GmbH
Urs Meier


mercatus GmbH
Rotlaubenstrasse 2
CH-5634 Merenschwand
+4156 640 01 41

**Comment by xamplo** [comment]
Could you perform the test on Android, as on Huaway I have issues due to the incompatibility.
If your tests are successfully, this issue can be closed
