### ISSUE TITLE
v1.7.0: created group not visible in browser app (in mobile app it's working)

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#145]
The just created group in the browser is not visible under "Manage Group" and can't be managed directly after.

![2017-07-27 20_16_38-aspecx _ app](https://user-images.githubusercontent.com/22747157/28685714-f3212f7a-7308-11e7-98f8-627edba1c78d.png)

![2017-07-27 20_17_27-aspecx _ app](https://user-images.githubusercontent.com/22747157/28685717-f5aa887c-7308-11e7-99d8-a59427a8ef21.png)

**Comment by ursmeier-mercatus** [comment]
Try clearing the cache in the browser, or press Shift on Refresh. 
Does this solve the problem?

**Comment by xamplo** [comment]
You are right. Thanks
