### ISSUE TITLE
1.7.0: what happen if rating date is due and no rating has been given

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#146]
The RatingDate is due (27.07). For this rating a notification has been sent out when the OpenDate = date().

The rating hasn't been executed by the user and today (28.07) no notification badge should be visible anymore (I ran the notification cronjob), but the notification badge number didn't decrease by 1.
Is this a bug ?

**Comment by ursmeier-mercatus** [comment]
This is the current implementation.
--> See mail "Info" from 05.07.2017

As mentioned, I would leave it this way.

Why?
a) Keep the user motivated to open the app and to find the "missed" ratings.

b) Between open_date and rating_date the user will most likely do the rating. 
Decreasing the badge is then done by the app. 
Decreasing the badge via Cron should be an exception.

c) Minimize traffic and number of messages. 
Implementing decreases would mean, that we have to calculate all users with all rating dates and notify them every day.

**Comment by xamplo** [comment]
a) difficult, as the user won't think about opening the app in such cases. They must be reminded

c) is THE reason to accept the implementation as it is done.
