### ISSUE TITLE
appintern: connected user doesn't see any data

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#149]
Users with their ID entered in the service file uid.json don't see any data in appintern, although they have groups created and currently open ratings.

test done with :
8UxDqQT7pEYAT7OYPKjp3OHZlT93
HL6UgI1GSsOkUfDARx4O34uZcm93 

Even with F5, Shift F5 and in a different browser it doesn't work anymore.

**Comment by ursmeier-mercatus** [comment]
Currently I see 8UxDqQT7pEYAT7OYPKjp3OHZlT93.
Changed UID and back. Both worked.
Shift-F5 needed after changes.

Do you get any errors in the Browser Console?

**Comment by xamplo** [comment]
I just tested appintern with firefox and Explorer at the Alpiq. Same results. I see no groups, although the user has groups managed.

![2017-08-02_16h05_52](https://user-images.githubusercontent.com/22747157/28877420-991b5418-779c-11e7-8b56-8fb59fde6946.png)

The issue are permissions. You have the permissions, that I am missing:

![2017-08-02_16h08_29](https://user-images.githubusercontent.com/22747157/28877547-00108710-779d-11e7-9874-6a34f590d38c.png)

**Comment by xamplo** [comment]
Even on Chrome I have no access to get all functions working.

![2017-08-02 20_59_18-groups](https://user-images.githubusercontent.com/22747157/28889821-90c814ee-77c5-11e7-8e81-6f85a8168eb1.png)

**Comment by ursmeier-mercatus** [comment]
Since `appintern` doesn't log-in, you have to open the `app` Webapp **first** and login there.
This would also explain, why sometimes it works (login token exists) and sometimes it doesn't.

Does this work for you?

**Comment by xamplo** [comment]
That was the issue. Now it works!

![2017-08-03 16_01_56-groups](https://user-images.githubusercontent.com/22747157/28925430-30a5e550-7865-11e7-973f-48db32d0f846.png)
