### ISSUE TITLE
Notification badge not woking for renamed users

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#150]
If a user has renamed his e-mail address, the notification badge won't work-

Test case:

1. user edo.bezemer@xamplo.com connects to aspecx
2. navigate to menu settings - account
3. rename e-mail from edo.bezemer@xamplo.com to hans.muster@xamplo.com
4. Next rating date: tomorrow
5. No notification badge the next day

**Comment by xamplo** [comment]
I just tested it again, and now it works.

- rename email: hans.muster@xamplo.com to edo.bezemer@xamplo.com
- **close** app
- create open rate date
- run cronjob
- result:ok (new badge)

- rename name: Hans Muster to Edo Bezemer
- **kill** aspecx
- create open rate date
- run cronjob
- result:ok

Even no errors in the function logs.

**Comment by xamplo** [comment]
It seems an issue on the server side. So we can now release the version 1.7.0?

**Comment by ursmeier-mercatus** [comment]
I didn't change anything. I wouldn't know why renaming the user should break the push notifications.

Deleting and re-installing the app on iOS breaks the push notifications. Maybe your first test was after an new installation of the app?

**Comment by xamplo** [comment]
Yes, that's true, I did the test after the installation of version 1.7.0. Today I did the test on 1.7.0 without new installing it.
