### ISSUE TITLE
1.7.1: names and owner of created groups not always visible

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#151]
After creating a group, leaving the menu "manage group" and re-opening the manage groups shows groups without names and administrator. Sometimes this information appears again. This on iphone 5, 6 and ipad.

iphone 6:
![img_4032](https://user-images.githubusercontent.com/22747157/28889688-16229412-77c5-11e7-90ac-ab674c731b2d.PNG)

iphone5 / ipad
![img_4033](https://user-images.githubusercontent.com/22747157/28889687-161d9c6e-77c5-11e7-8f2e-016447b9337a.JPG)

**Comment by xamplo** [comment]
Browser view:
![2017-08-02 21_01_05-aspecx _ app](https://user-images.githubusercontent.com/22747157/28889907-c6b095f4-77c5-11e7-8b9f-ba8e819d7cb3.png)

**Comment by ursmeier-mercatus** [comment]
The group "Test notification" was missing in the database in "/groups":
Added:


<img width="487" alt="bildschirmfoto 2017-08-03 um 12 23 52" src="https://user-images.githubusercontent.com/22747183/28917717-e0f81c94-7846-11e7-8b26-94ebaffd42d1.png">

This should fix the problem.
Don't know, how and why the entry was deleted. The app only sets the flag to "inactive", when deleting a group.

Once the "undefined" entry of the missing group was hit, the code stopped and the other groups showed also nothing.

**Comment by xamplo** [comment]
Works now
