### ISSUE TITLE
Recommended number of aspects per group

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#16]
The app should provide do's and don't including the recommended number of aspects per group (5-7)

**Comment by xamplo** [comment]
Please add the proposal to define maximal 5 aspects within the text on the rating page:
It's recommended to define 5 maximum aspects per group.

**Comment by ursmeier-mercatus** [comment]
done in 1.0.3

**Comment by xamplo** [comment]
Works in the version 1.03
