### ISSUE TITLE
Password field not visible

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#2]
After entering the username there is still no field visible to enter the password
![2016-10-14 21_55_53-](https://cloud.githubusercontent.com/assets/22747157/19401009/1c76790c-9259-11e6-9abe-bbe2aa48aa8b.png)

**Comment by xamplo** [comment]
Wrongly closed this issue

**Comment by ursmeier-mercatus** [comment]
Android keyboard pushes the ion-footer. Temporarily removed the footer. Problem will be solved in register page
