### ISSUE TITLE
Number of raters = 1, although no rates have been provided

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#23]
![2016-11-06 10_23_26-airdroid web _ manage your phone on web](https://cloud.githubusercontent.com/assets/22747157/20036580/f062cce8-a40b-11e6-9940-503c753c68ae.png)

**Comment by xamplo** [comment]
in case more rates have been received (starting from 2), the numbers of rates are correct. It's only a bug for rates <=1.

**Comment by ursmeier-mercatus** [comment]
Wrong scale in animation, animation starts now at 0
Fixed: 0.8
