### ISSUE TITLE
aspect not rated as negative, however it is shown in the negative dashboard

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#24]
If possible (time, effort, logic) it should be better to only show the aspects that have been rated in the related dashboards. If an aspect is rated as positive it could be shown in the positive dashboard, if the aspects is not rated as negative, it should not shown in the negative dashboard, as it is not negatively perceived as such

**Comment by ursmeier-mercatus** [comment]
It is the average, that counts. You will also see aspects with no + ratings, showing up in the most+ ratings, e.g.
If you rate
A1=8 
A2=5
A3=3

The two most+ are: A1, A2
The two most- are: A3, A2

So, it is not important if A2 has + or - ratings. The average is 5 and it show once in + and once in -

I would not change the rules. This will end up in confusing ratings.

**Comment by xamplo** [comment]
Agree.
