### ISSUE TITLE
USER TEST FEEDBACK: usability is better if the first field is activated automaticlly

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#25]
According the first user feedback, the usability will be increased if the first field of the corresponding forms is activated. This considers:

- to register new user
- to login
- to create group
- to create aspect
- to invite new member

**Comment by xamplo** [comment]
Feedback is from Sibylle's mother

**Comment by ursmeier-mercatus** [comment]
Good point, but in order to be useful the keyboard must be activated immediately.
This will hide most of the form (help text, main button etc.).

v0.8
I will make an example in Admin Groups+

**Comment by xamplo** [comment]
Good point. So we can test it for the groups in version 0.8

**Comment by xamplo** [comment]
Will be redo, as the keyboard overlaps all functions and a warning appears if the field is not immidiately filled

**Comment by ursmeier-mercatus** [comment]
removed focus in group create
