### ISSUE TITLE
USER TEST FEEDBACK: the red informations/warnings have been intepreted as buttons

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#26]
Each time a red information block is shown, it has been tried to click on it

![2016-11-06 10_55_30-airdroid web _ manage your phone on web](https://cloud.githubusercontent.com/assets/22747157/20036692/94ce0cf4-a40f-11e6-96ba-b8d451a84dac.png)

**Comment by ursmeier-mercatus** [comment]
Going back to red text?

**Comment by xamplo** [comment]
Yes, makes sense. Perhaps with bold font and/or a bigger font?

**Comment by ursmeier-mercatus** [comment]
Red, light-bold, italic in v0.8
closing for the moment
