### ISSUE TITLE
Rate values should be shown in standarized format

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#27]
Overall rate: 2 digits after the comma
Neg/Pos rates: 0 digits after the comma

![2016-11-06 11_01_02-airdroid web _ manage your phone on web](https://cloud.githubusercontent.com/assets/22747157/20036723/7c419510-a410-11e6-9e35-8dc1c2aa9513.png)

**Comment by xamplo** [comment]
I suggest the format #,0 
One digit after the comma: 3.5  4.0

**Comment by ursmeier-mercatus** [comment]
Fixed: 0.8
