### ISSUE TITLE
Numbers are overlapping in the dashboard and are nor readable anymore

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#29]
Workarround is to deactivate the aspects by the end user (clicking on the legend)

![2016-11-06 11_12_37-airdroid web _ manage your phone on web](https://cloud.githubusercontent.com/assets/22747157/20036780/138134ca-a412-11e6-826f-df3859d024dd.png)

**Comment by ursmeier-mercatus** [comment]
Solutions:
1) Show 2 Bars (I find this confusing, because there are 2 different measures which ask for 2 different styles)

2) Show 2nd Scale and hide Data Labels in diagram (I find this harder, no precise, to read)

3) ?

**Comment by xamplo** [comment]
Both options are from my point of view not bringing an added value to the users.

Proposal:
3) we show a hint directly under the legend saying somethin like: "By clicking on the legend, the different graphics can be hidden or shown"
