### ISSUE TITLE
Entering date in the past show 2 error messages

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#3]
![2016-10-14 22_07_11-lonelyscreen airplay receiver](https://cloud.githubusercontent.com/assets/22747157/19401298/d1095a32-925a-11e6-99a9-d1cdce72bc1f.png)

**Comment by ursmeier-mercatus** [comment]
Works as designed. 
There are 2 validators, the range validator is invalid, when either of the dates are invalid.
Fixed: Not showing 2nd validator for Range, if first Rating Date is invalid anyway

**Comment by xamplo** [comment]
Only background color change
