### ISSUE TITLE
Counter of invitations = 5, although only 1 initation is open

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#30]
![2016-11-06 11_20_12-airdroid web _ manage your phone on web](https://cloud.githubusercontent.com/assets/22747157/20036812/25a0a90a-a413-11e6-8121-4864918212b7.png)

![2016-11-06 11_20_33-airdroid web _ manage your phone on web](https://cloud.githubusercontent.com/assets/22747157/20036813/2934544a-a413-11e6-8190-697ba7d730d0.png)

**Comment by xamplo** [comment]
The number of open ratings is for this user 16 (but that you already explained way)

**Comment by ursmeier-mercatus** [comment]
Any more infos on this? Can you reproduce the issue?

**Comment by xamplo** [comment]
I will redo the test

**Comment by xamplo** [comment]
I couldn't reproduce this item

**Comment by xamplo** [comment]
Will open a new issue if it ocurs again
