### ISSUE TITLE
After 5 rates, the most pos/most neg rating results are not diplayed correctly

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#31]
After entering the 5th rate for the group, the overall rating is correct, the most positive and most negative are showing only the last rating results.

![2016-11-06 11_28_30-airdroid web _ manage your phone on web](https://cloud.githubusercontent.com/assets/22747157/20036846/3d901810-a414-11e6-8c77-5e4f0c4cf92d.png)

**Comment by xamplo** [comment]
The 6th rate is showing the right values but the wrong rates

![2016-11-06 11_39_10-airdroid web _ manage your phone on web](https://cloud.githubusercontent.com/assets/22747157/20036897/c08210c4-a415-11e6-8d4a-d60a48ec4fe7.png)

**Comment by xamplo** [comment]
![2016-11-06 11_51_25-aspecx_user_and_test_cases_20160105 xlsx - excel](https://cloud.githubusercontent.com/assets/22747157/20036947/661f2f34-a417-11e6-940e-81e5f88bbc4a.png)

**Comment by ursmeier-mercatus** [comment]
Not sure, if I understand the issue correctly. Do you expect the sum of raters to sum up to the total of raters?
Raters of aspects don't have to sum up to the total of raters, because you only see _two_ aspects.

**Comment by xamplo** [comment]
Until 5 rates everything went well. After rater nr.5 provided his rates, the dashboards showed incorrect data as illustrated in the print screens above. The most positive and the most negative dashboard showed only the rate results of the 5th rater.

No sums are expected.

I will redo this test and report the results.

**Comment by xamplo** [comment]
Test successfully.

I assume during my first test I have used not consistently the same due date rates. 
![2016-11-06 21_29_39-aspecx_user_and_test_cases_20160105 xlsx - excel](https://cloud.githubusercontent.com/assets/22747157/20041382/62222e8a-a468-11e6-98a9-da6d244fda06.png)

**Comment by xamplo** [comment]
Issue can be closed
