### ISSUE TITLE
Raters window: First rater is the owner. Adding "(you)" or "(owner)" after the admin name could reduce confusion

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#32]
To flag the name of the owner could help the user to know who is behind the name. It could very well be, that the group contains more Edo's
The list with the raters could look like
Urs (you)
Sibylle
Urs
Edo

or 

Urs (group owner)
Sibylle
Urs
Edo

![2016-11-06 20_45_14-](https://cloud.githubusercontent.com/assets/22747157/20041022/b0f6f7f8-a462-11e6-8012-a5498ba0c2b4.png)

**Comment by ursmeier-mercatus** [comment]
v. 0.8 shows the email and allows to send emails directly to raters/invited persons

**Comment by xamplo** [comment]
Wow! Thanks.
