### ISSUE TITLE
USER FEEDBACK: Rate group renamed to "aspecx group"?

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#33]
Rater group is unclear, as the group is an aspecx group.

Could it be an idea to use more the wording aspecx, like Whatspp. Here we speak about a WhatsApp group, using the name of the app.

The title is aspecx group. I would use "aspecx group" more consistent,

![2016-11-06 21_06_43-](https://cloud.githubusercontent.com/assets/22747157/20041137/4f9c874a-a465-11e6-9da5-f14ec5b1113b.png)

**Comment by ursmeier-mercatus** [comment]
I agree, the names are not yet good.
I was thinking about
"Groups, where I am a rater" = "Groups, I rate"
"Groups, where I am an admin" = "Groups, I administer"

but these names are too long, of course.

aspecx groups vs. admin groups doesn't show the difference well enough in my opinion.

Need a better name

**Comment by xamplo** [comment]
Proposal:
![2016-11-07 06_54_40-4f9c874a-a465-11e6-9da5-f14ec5b1113b png png image 395 x 706 pixels](https://cloud.githubusercontent.com/assets/22747157/20047833/39f74ce2-a4b8-11e6-860e-97f8e7015854.png)

**Comment by ursmeier-mercatus** [comment]
The minimalistic approach would be:
![bildschirmfoto 2016-11-07 um 17 15 02](https://cloud.githubusercontent.com/assets/22747183/20065282/d5ba2406-a50d-11e6-8e8d-b84ccd79fe58.png)

What do you think?

**Comment by xamplo** [comment]
Gefällt mir. So ist es auch skalierbar wenn die Rolle Viewer dazu kommt. GrussEdo-------- Originalnachricht --------Betreff: Re: [xamplo/aspecx] USER FEEDBACK: Rate group renamed to "aspecx group"? (#33)Von: ursmeier-mercatus An: xamplo/aspecx Cc: xamplo ,Author The minimalistic approach would be:

What do you think?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xamplo/aspecx","title":"xamplo/aspecx","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/xamplo/aspecx"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ursmeier-mercatus in #33: The minimalistic approach would be:\r\n![bildschirmfoto 2016-11-07 um 17 15 02](https://cloud.githubusercontent.com/assets/22747183/20065282/d5ba2406-a50d-11e6-8e8d-b84ccd79fe58.png)\r\n\r\nWhat do you think?"}],"action":{"name":"View Issue","url":"https://github.com/xamplo/aspecx/issues/33#issuecomment-258880978"}}}
