### ISSUE TITLE
Showing error messages with a colored background

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#4]
Message is difficult to read. Text should be bigger and a backgroud collor should help
![2016-10-14 22_11_37-lonelyscreen airplay receiver](https://cloud.githubusercontent.com/assets/22747157/19401381/5ea683ba-925b-11e6-8b38-15fbb5df69e5.png)

**Comment by ursmeier-mercatus** [comment]
done: red background (danger color) with white font
