### ISSUE TITLE
Testflight test: Keyboard doesn't appear after pressing the enter button on the keyboard

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#47]
After entering content in fields and completing the action by clicking on the "Öffnen" or "Enter" button within the keyboard, the keyboard doesn't appear on the iphone. On Android it's working

![2016-11-17 06_22_42-lonelyscreen airplay receiver](https://cloud.githubusercontent.com/assets/22747157/20377295/8200ba72-ac8e-11e6-99bf-3df10d999ea6.png)

**Comment by ursmeier-mercatus** [comment]
Fixed in 0.9.3.
- group
- aspect
- rater invitation
- login
- register
