### ISSUE TITLE
Deleting a member or deleting an aspect, a confirmation message is missing

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#48]
Like if a group is deleted, a confirmation message appears, as the user could have press the delete button by accident

**Comment by ursmeier-mercatus** [comment]
Confirming a deletion is in my opinion an historical issue with keyboard, where a  user could accidentally hit the delete-button. Confirmation makes a two-step-process.
Sliding and hitting delete is a already a two-step-process. Usually this does not require a confirmation (e.g. deleting sms).
I would leave it this way.

**Comment by ursmeier-mercatus** [comment]
Done with action sheet in 1.0.1
