### ISSUE TITLE
Testflight: Editing a group by using the slide function results in keeping the slide button opened

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#49]

**Comment by xamplo** [comment]
The slide function should close again after leaving the edit mode

![2016-11-17 06_28_07-lonelyscreen airplay receiver](https://cloud.githubusercontent.com/assets/22747157/20377364/2077d578-ac8f-11e6-9e8b-a14af278aa12.png)

**Comment by ursmeier-mercatus** [comment]
Fixed: 0.9.3
