### ISSUE TITLE
Rating overview is not in line with the other screen concept

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#5]
Sibylle her first reaction: "Eisenbahn?"

The collors green and red and the hand symbols are good ideas. The big fields are no to the other fields of the app, should be more delicate.

![2016-10-14 22_18_26-lonelyscreen airplay receiver](https://cloud.githubusercontent.com/assets/22747157/19401605/7b18118e-925c-11e6-9c11-bb7d0a376d96.png)

**Comment by xamplo** [comment]
The function of the arrow is not clear.

Perhaps an idea to to color the background of the text "Choose most positive..." (now it's blue) with 0CF0B8 (Farbregel "ähnlich) and the background of the text Choose most negative..." E81739 /Farbregel triade) instead.

![2016-10-14 22_22_48-airdroid web _ manage your phone on web](https://cloud.githubusercontent.com/assets/22747157/19401666/e4f33552-925c-11e6-996d-6806667a427e.png)

**Comment by xamplo** [comment]
The text "Rating x" is misleading. Is it the 7th rating?
Could it be possible to show the number somewhere in the slide?
I like the first 2 range symbols better in: http://ionicframework.com/docs/v2/components/#range

**Comment by xamplo** [comment]
I think it's better to select the aspect in a selection list:
http://ionicframework.com/docs/components/#select

**Comment by ursmeier-mercatus** [comment]
Changed to softer color, and cards are closed until button is pressed
