### ISSUE TITLE
Testflight: Editing a group should alos include editing all parameters

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#50]

**Comment by xamplo** [comment]
Currently only the group name can be edited, but frequency not

![2016-11-17 06_27_48-lonelyscreen airplay receiver](https://cloud.githubusercontent.com/assets/22747157/20377384/6c0edf72-ac8f-11e6-8bb3-acd5d851867d.png)

**Comment by ursmeier-mercatus** [comment]
It is complicated to change dates or frequency. As long as there no ratings it could be made (still some work to be done), but as soon as there are ratings it will be almost impossible. For instance, how to show a decent history, if the interval changes from week to month?

I suggest, to keep it this way. If the settings are wrong, the a new group must be created

**Comment by xamplo** [comment]
The HR Stratege has given the feedback, that it should be very helpful, in case the rating frequency could be changes in case of a heavy, intensive or very calm period of time
