### ISSUE TITLE
Testflight: If Email alrerady exists, misleading warning message 

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#51]
Message is saying: "Email not allowed". Should be something like "An account with this Email already exists"

 
![img_2543](https://cloud.githubusercontent.com/assets/22747157/20424178/cb96b736-ad74-11e6-9885-4a9f4ff4cca8.PNG)

**Comment by ursmeier-mercatus** [comment]
This is on purpose for security reasons.
So that other users cannot easily guess email addresses.
Stating that an email already exists, clearly confirms an existing address.

**Comment by xamplo** [comment]
understand and is a good idea
