### ISSUE TITLE
Testflight: Members want to see who the other raters are

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#52]
Currently the raters don't see the other raters.

**Comment by ursmeier-mercatus** [comment]
Where?

**Comment by xamplo** [comment]
Either somewhere in the dashboard as separate register?
In this register the target of the group could be listed as well as the members of the group.

**Comment by ursmeier-mercatus** [comment]
Oh, I misunderstood the issue.

Suggestion:
1) The admin gets a switch on the group to make the member list public (default: true)
2) In the Invitation-Menu on the group the action-sheet gets a new item "Show Members" (always)
3) If the member-list is not public -> 1) then the user sees a corresponding message.

**Comment by ursmeier-mercatus** [comment]
Done: 0.9.6
Group Details Page, currently accessible from Invitation Page
Raters are currently always public (everyone can see all other raters)
