### ISSUE TITLE
Testflight: Generate pdf or much better Excel of dashboards

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#55]
Hietr einzelne Links zu dem Thema
http://codepen.io/jdnichollsc/pen/ZbXawy
https://github.com/jeffleus/ionic-pdf

**Comment by ursmeier-mercatus** [comment]
I suggest, that we add an export which can be mailed.

**Comment by xamplo** [comment]
Good idea!

**Comment by ursmeier-mercatus** [comment]
**## Proposal for next release:**
a) Only admin can mail statistics
b) Add "Manage Groups" --> Action-Sheet --> Export Statistics 
c) Generate File and open mail dialog with attachment

**Comment by xamplo** [comment]
The development of the aspecx statistics toolbox has been completed and works on MS Office 2010 and higher. 
http://aspecx.biz/documents/template_aspecx_dashboard.xlsm
