### ISSUE TITLE
Testflight: End user want to see the objective of the group

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#59]
It would be very helpful to click on the group name in the ratings, subsequently a window or text appears with the objectives of the group or a short description and the members of the group as mentioned in
https://github.com/xamplo/aspecx/issues/52

**Comment by ursmeier-mercatus** [comment]
We could display the group description.
Should it appear in the "todo"-list, or in the rating page itself?

**Comment by xamplo** [comment]
I would do it in the rating itself, as otherwise the to do list will lose its simplicity, depend on the amount of text the group description/target will contain

**Comment by ursmeier-mercatus** [comment]
Done: 0.9.6
Group Details Page, currently only accessible from Invitation Page
