### ISSUE TITLE
Logout Text

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#6]
I would get rid of the text "Really logout" and replace the text on the button "LOGOUT" with "CONFIRM LOGOUT"
![2016-10-14 22_53_58-airdroid web _ manage your phone on web](https://cloud.githubusercontent.com/assets/22747157/19402408/40f09d28-9261-11e6-9f9e-1eff6825af39.png)

**Comment by ursmeier-mercatus** [comment]
done
