### ISSUE TITLE
Legend overwrites the aspect names in the overview dashboards

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#64]
![2016-11-28 08_05_31-img_2548 png - fotos](https://cloud.githubusercontent.com/assets/22747157/20659079/aa14c024-b541-11e6-8d6d-e92e9ea28daa.png)

**Comment by ursmeier-mercatus** [comment]
The space between data-labels and the legend is fixed, not dynamic. 
I put some more space in between, but I might not be sufficient for very looooong labels.
Fixed in 0.9.6
