### ISSUE TITLE
Test user: Invitation menu missing

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#65]
Version 903

![screenshot_2016-11-28-13-24-43](https://cloud.githubusercontent.com/assets/22747157/20668344/aec6c46e-b56e-11e6-8b83-afd3c685d6b8.png)

**Comment by ursmeier-mercatus** [comment]
Always missing, or under certain conditions?

**Comment by xamplo** [comment]
On my android I didn't have the issue.
Until now after the installation and during the search of finding where to accept the invitation. Finally he could accept the invitation under the menu manage groups

**Comment by ursmeier-mercatus** [comment]
OK. I think the user has a very old version.
The Group-Menu does not exist anymore.

**Comment by xamplo** [comment]
And something like this:

![login_proposal_2](https://cloud.githubusercontent.com/assets/22747157/20671747/e78813ec-b57e-11e6-9f5c-045647815a67.png)

**Comment by xamplo** [comment]
Here I didn't consider the complementary colors...

**Comment by ursmeier-mercatus** [comment]
I'll move it to top. Doesn't do any harm an we decide later.
