### ISSUE TITLE
Test user: First access to app difficult to understand what to do

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#66]
After receiving the invitation for a new group, the very new aspecx user was confused to do what. He entered an email address and "a" password, which where invalid as the user wasn't yet registered.

Proposal:
Login window recognizes whether the email has already been registered, If not, automatically the registration form will be shown.

**Comment by ursmeier-mercatus** [comment]
Could we start with the register form? A registered user will usually not have to login again, and if he does, he knows that he as already registered.

**Comment by xamplo** [comment]
Yes, could be an option, in case the email address is not registered?

For users who frequently connect to the app, this register form is an extra click and makes the app less user-friendly

Or another option as mentioned in the initial requirement catalogue:
![login_proposal](https://cloud.githubusercontent.com/assets/22747157/20670857/3eeb06de-b57b-11e6-815b-1be9f7fdea24.png)

**Comment by ursmeier-mercatus** [comment]
We could move "Not a member? Register now" to the top of the screen.

**Comment by xamplo** [comment]
Or something like

![login_proposal_2](https://cloud.githubusercontent.com/assets/22747157/20672122/6a2a42e2-b580-11e6-8047-91bfd6be6d45.png)

**Comment by ursmeier-mercatus** [comment]
Proposal with 0.9.6
re-open, if not good.
