### ISSUE TITLE
Terms & Privacy Policies links should be shown

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#67]
terms: http://aspecx.biz/terms.html
Privacy policy: http://aspecx.biz/policy.html

**Comment by ursmeier-mercatus** [comment]
Terms are currently on the register screen. 
I can add the Privacy Policy there, too.

We should remove the orange help text.

**Comment by xamplo** [comment]
I agree, text can be removed

**Comment by ursmeier-mercatus** [comment]
Done: 0.9.6
