### ISSUE TITLE
reset password doesn't work

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#69]
After pressing the Reset password button, nothing happens. Nor on android neither on ios.

![screenshot_2016-11-30-15-46-13](https://cloud.githubusercontent.com/assets/22747157/20756884/a9b7ff9a-b714-11e6-8232-fde560374f9f.png)

**Comment by ursmeier-mercatus** [comment]
Uiih, configuration error after installation ionic rc3.
Bug in ionic app-scripts0.0.46 -> Error cannot find variable Firebase, when accessing Firebase directly, not via angularfire2, which is necessary for Passwort-Reset.
Downgraded to ionic app-scripts0.0.45

Fixed in 1.0.1
