### ISSUE TITLE
testflight: Can't change name of an existing group

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#71]
The save button keeps inactivated after changing the group name

![2016-12-04 11_24_29-lonelyscreen airplay receiver](https://cloud.githubusercontent.com/assets/22747157/20865502/db8ddba4-ba14-11e6-93d3-51cbbe2b74b1.png)

**Comment by xamplo** [comment]
On the Released Test Android version it is properly working

**Comment by ursmeier-mercatus** [comment]
Fixed in 1.0.1
Can you edit 2x in a row on Android?

**Comment by xamplo** [comment]
Yes, I can do this in Android. 
I just found out, that renaming groups is only possible with new created groups, even in IoS. Older groups on IOS is not possible

**Comment by ursmeier-mercatus** [comment]
>Yes, I can do this in Android.
On iOS it didn't work for me.

>I just found out, that renaming groups is only possible with new created groups
This is the fix in 1.0.1

**Comment by ursmeier-mercatus** [comment]
Note: 
2 edits in a row hang with an "open" subscription.
Could be related to software upgrade angularfire2@2.0.0-beta.6

**Comment by ursmeier-mercatus** [comment]
It is definitely an angularfire2 issue and should be solved with beta7.
https://github.com/angular/angularfire2/issues/574

**Comment by xamplo** [comment]
is it known, when beta 7 will be available?

**Comment by ursmeier-mercatus** [comment]
No date given.
https://github.com/angular/angularfire2/milestone/13
