### ISSUE TITLE
Tstflight: Headers of the group related windows is confusing

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#72]
It's seems confusing to know in which menu the user currently is. This related only to the group menus.
After clicking in the main menu on groups, the header of the opened window is "Groups"
After clicking in the main menu on manage groups, the header of the opened window is "aspecx Groups"

Proposal:
Header of "Groups" is "Groups"
Header of "aspecx Groups" is "Manage Groups"

**Comment by ursmeier-mercatus** [comment]
Haven't seen this issue, but changed the titles on my own.
So, the titles are different, but hopefully OK.
Please check again.

**Comment by xamplo** [comment]
Now it's consistent
