### ISSUE TITLE
Behavior renamed aspects

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#73]
What is the expected behavior of a renamed aspect. Currently the renamed aspect seems to be a new aspects with a new unique identifier and is shown as a new aspect.

Is this consequence as designed?

I was actually the opinion, that the renamed aspect appears as an existing aspect with only a new name

![2016-12-04 12_09_25-lonelyscreen airplay receiver](https://cloud.githubusercontent.com/assets/22747157/20865769/a0b64758-ba1b-11e6-944d-e3d15ed6a044.png)

![2016-12-04 12_13_07-lonelyscreen airplay receiver](https://cloud.githubusercontent.com/assets/22747157/20865771/a5ed5130-ba1b-11e6-9603-de411bcba565.png)

![2016-12-04 12_14_01-lonelyscreen airplay receiver](https://cloud.githubusercontent.com/assets/22747157/20865773/ad0e014e-ba1b-11e6-8d1f-8989c303c7d6.png)

**Comment by ursmeier-mercatus** [comment]
Currently, we aggregate by key. This is probably the meaning of renaming an aspect.
e.g.  renaming a typo, consolidates data under the new, correct name.
I will send you the documentation (page 19).
