### ISSUE TITLE
Testflight: re-inviting deleted or rejected raters not possible

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#74]
![2016-12-04 12_44_17-lonelyscreen airplay receiver](https://cloud.githubusercontent.com/assets/22747157/20865946/f8e466b8-ba1f-11e6-8cee-cc3549683651.png)

![2016-12-04 12_44_39-lonelyscreen airplay receiver](https://cloud.githubusercontent.com/assets/22747157/20865947/fb57b67a-ba1f-11e6-8a42-a3ea21268f28.png)

![2016-12-04 12_49_30-lonelyscreen airplay receiver](https://cloud.githubusercontent.com/assets/22747157/20865951/228b0c1a-ba20-11e6-843b-bbb732742865.png)

**Comment by ursmeier-mercatus** [comment]
This is by design, so that the admin cannot send, re-send, re-re-send ... invitations to users who do not accept invitations.
On the the other hand, the user can accept an invitation, even if he has rejected it beforehand.
