### ISSUE TITLE
Standardize and facilitate the swipe function

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#76]
Either we could get rid of the swipe function or we could provide the same functions in the swipe function as in the functions in the pop-up menu

**Comment by ursmeier-mercatus** [comment]
Currently, "destructive" actions are "hidden" in the swipe-menu.
(Exception: invitation). 
Editing/renaming needs a good understanding and users should not easily have access to it.

**Comment by ursmeier-mercatus** [comment]
All swipes are eliminated with the exception of accepting invitations. But there is an action menu, too.
