### ISSUE TITLE
reset password: sender must be renamed (on prod development)

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#77]
![2016-12-09 20_54_53-](https://cloud.githubusercontent.com/assets/22747157/21062588/e6e9be82-be51-11e6-9b73-622954f2a7fc.png)

**Comment by ursmeier-mercatus** [comment]
console.firebase -> Authentication -> Email Templates.
Needs DNS entries in the hosting environment:
Host	Typ	Wert
aspecx.biz	TXT	v=spf1 include:_spf.firebasemail.com ~all
smtpapi._domainkey.aspecx.biz	TXT	k=rsa; t=s; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDPtW5iwpXVPiH5FzJ7Nrl8USzuY9zqqzjE0D1r04xDN6qwziDnmgcFNNfMewVKN2D1O+2J9N14hRprzByFwfQW76yojh54Xu3uSbQ3JP0A7k8o8GutRF8zbFUA8n0ZH2y0cIEjMliXY4W4LwPA7m4q0ObmvSjhd63O9d8z1XkUBwIDAQAB
aspecx.biz	TXT	firebase=aspecx-189d7

**Comment by xamplo** [comment]
works in prod perfectly
