### ISSUE TITLE
Optimization Text invitation Email 

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#79]
**Current:**
You are invited to join the aspecx group "Project Team Digitalisation".

This group has defined aspects (values), that will be regularly rated with the objective to continuously improve the related quality and performance.

Your contribution to rate the defined aspects is highly appreciated. Providing your ratings should be done by using the mobile app aspecx.
You can accept this invitation in the aspecx app.

Not yet using aspecx? Install the aspecx App

Thank you!

**New:**
You are invited to join the aspecx group "Project Team Digitalisation".

This group has defined aspects **(e.g. values or goals)**, that will be regularly rated with the objective to continuously improve the related quality and performance.

Your contribution to rate the defined aspects is highly appreciated. Providing your ratings should be done by using the mobile app aspecx.
**You can only accept this invitation in the aspecx app.**

Not yet using aspecx? Install the aspecx App

Thank you!

**Comment by ursmeier-mercatus** [comment]
Proposal to include the needed email address for registering/login with aspecx as well:
Done in 1.0.3

You are invited to join the aspecx group **"Bid group"**.

This group has defined aspects (e.g. values or goals), that will be regularly rated with the objective to continuously improve the related quality and performance.

Your contribution to rate the defined aspects is highly appreciated. Providing your ratings should be done by using the mobile app aspecx.
**Please accept this invitation in the aspecx app using your email address urs.meier@mercatus.ch** 

Not yet using aspecx? Install the aspecx App

Thank you!

**Comment by xamplo** [comment]
Works in the version 1.03
