### ISSUE TITLE
Creating Group Start Date in the past,results in that the group exists from that date

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#80]
This information is incorrect (can be accepted for the first release).
Creation date should always be at least today() - 7 days.

![2016-12-09 21_27_32-](https://cloud.githubusercontent.com/assets/22747157/21063590/b1b344d6-be56-11e6-867c-92ddaae87ba0.png)

**Comment by ursmeier-mercatus** [comment]
Duplicate of #81.
We cannot create a group < today.
