### ISSUE TITLE
Last Rating Date in the past doesn't show a corresponding message

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#81]
The "Add Group" button is de-activated however no message appears why the group can't be created.

This bug can be accepted for the first release, as the number of rates (=0) shows that no rates can be executed.

![2016-12-09 21_35_03-](https://cloud.githubusercontent.com/assets/22747157/21063781/bcbdd5c0-be57-11e6-9de5-08ade665d30c.png)

**Comment by ursmeier-mercatus** [comment]
Start date was not validated anymore.
Fixed in 1.0.3

**Comment by ursmeier-mercatus** [comment]
Reopening for testing for MS 1.1

**Comment by xamplo** [comment]
Works in the version 1.03
