### ISSUE TITLE
Deleting a rater doesn't cancel his ability to provide rates and access to the group

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#84]
The member disappears on the group admin site, the rater doesn't know and can't noticed whether he has been deleted.

If possible, this bug should be fixed before going life

User has been deleted in the Test group:
![2016-12-09 22_24_12-lonelyscreen airplay receiver](https://cloud.githubusercontent.com/assets/22747157/21064981/4a42fad2-be5e-11e6-9a94-6a6232d39247.png)

But the deleted user sees his rates and is able to provide his rate:
![2016-12-09 22_22_58-](https://cloud.githubusercontent.com/assets/22747157/21064987/5ab27a3c-be5e-11e6-8eea-0247a45f681a.png)

**Comment by xamplo** [comment]
Deleted rate has still access to the group he has been revoked from:
![2016-12-09 22_33_04-](https://cloud.githubusercontent.com/assets/22747157/21065265/9b5b8bf4-be5f-11e6-9ca2-38b5a5de5a78.png)

**Comment by ursmeier-mercatus** [comment]
I cannot reproduce this.
a) create group
b) invite other person
c) other person accepts
d) admin deletes other person
OK

Are you doing the same?

**Comment by xamplo** [comment]
Hi UrsJa, habe da höchstwahrscheinlich den Admin selber gelöscht. Die letzten 2 Tests waren erfolgreich und die Rates verschwunden aus der Ratingliste on the fly.Sorry für die Verwirrung.GrussEdo -------- Originalnachricht --------Betreff: Re: [xamplo/aspecx] Deleting a rater doesn't cancel his ability to provide rates and access to the group (#84)Von: ursmeier-mercatus An: xamplo/aspecx Cc: xamplo ,Author I cannot reproduce this.
a) create group
b) invite other person
c) other person accepts
d) admin deletes other person
OK
Are you doing the same?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xamplo/aspecx","title":"xamplo/aspecx","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/xamplo/aspecx"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ursmeier-mercatus in #84: I cannot reproduce this.\r\na) create group\r\nb) invite other person\r\nc) other person accepts\r\nd) admin deletes other person\r\nOK\r\n\r\nAre you doing the same?"}],"action":{"name":"View Issue","url":"https://github.com/xamplo/aspecx/issues/84#issuecomment-266205342"}}}

**Comment by ursmeier-mercatus** [comment]
Oh, yes. I forgot that I have introduced a small log.
You deleted the admin, indeed: "who" is same as "params/uid

![bildschirmfoto 2016-12-10 um 15 27 19](https://cloud.githubusercontent.com/assets/22747183/21073958/60afbe56-beed-11e6-96e2-f21540a1d5cd.png)
