### ISSUE TITLE
firebase license upgrade or backup solution with CLI

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#88]
https://firebase.google.com/pricing/

**Comment by xamplo** [comment]
As the number of users is very few, I keep the daily backup as it is configured by default

**Comment by ursmeier-mercatus** [comment]
Backups are only available with the payable Blaze-Version of Firebase. Or am I wrong?

I added a small script to backup the data. 
<img width="1009" alt="bildschirmfoto 2017-02-06 um 12 34 14" src="https://cloud.githubusercontent.com/assets/22747183/22645705/a30b5d48-ec68-11e6-8308-e8ab4387e6e8.png">

The job is executed at 03:05 am and you will receive an email ;-)
(you can disable the email, if you want). The email is always sent: on success and on error.
No error handling in the script.

<img width="568" alt="bildschirmfoto 2017-02-06 um 12 35 43" src="https://cloud.githubusercontent.com/assets/22747183/22645766/effaf1ae-ec68-11e6-8096-9757819fecfe.png">


This is a temporary solution until we upgrade to Blaze.

**Comment by xamplo** [comment]
Urs, da hast du völlig recht. Ich habe da einen falschen Forum-Eintrag gelesen und war von automatischen Backups ausgegangen, auch für die gratis Lösung. Das war dumm!

 

 

Vielen Dank!!!!

 

 

Gruss

Edo

**Comment by xamplo** [comment]
Very good, Urs, its working. 
At the next opportunity, I will write a purge scripts for the backup files if the file has at least a specific size (validation) and is older than 1 month.

**Comment by ursmeier-mercatus** [comment]
I would keep them a very long time or forever as long as they don't take much space.
The purge method should then go into the php-script.
