### ISSUE TITLE
password reset: validation input text

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#95]
If entering blanks at the end of the email address, **sometimes** no action takes place. The app doesn't validate the entry text

Request to implement a function that validate the password reset input.

**Comment by ursmeier-mercatus** [comment]
Added the firebase error message for next release.

**Comment by xamplo** [comment]
The text "the email adress is badly formatted" could be confusing. I would propose to use: "Email not accepted, as it contains wrong characters (e.g. blanks)"

**Comment by ursmeier-mercatus** [comment]
This is the standard Firebase message. 
All standard Firebase messages will be a problem, when we have to translate the app. I would wait until then.
