### ISSUE TITLE
Include promotion code in android app

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#97]
In order to provide promotion codes on Android, the app must call the getPurchases() method.

https://developer.android.com/google/play/billing/billing_promotions.html

**Comment by ursmeier-mercatus** [comment]
getPurchases() is for in-app purchases only. We don't have in-app products to sell.
check: https://support.google.com/googleplay/android-developer/answer/6321495

In-App-Käufe: Wenn Sie Gutscheincodes für In-App-Käufe anbieten möchten, müssen Sie In-App-Werbeaktionen in die App integrieren. Beachten Sie, dass Gutscheincodes nicht für Abos oder inaktive In-App-Produkte verwendet werden können.

**Kostenpflichtige Apps: Wenn Sie Gutscheincodes für kostenpflichtige Apps anbieten möchten, können Sie diesen Schritt überspringen und mit Schritt 2 fortfahren.**

**Comment by xamplo** [comment]
Das tönt besser, hatte ich es falsch verstanden. Danke
