### ISSUE TITLE
Notification for rating due date 

### ISSUE THREAD

**Issue by xamplo** [xamplo/aspecx#98]
Could be a calendar entry and/or a notification on the mobile phone

**Comment by ursmeier-mercatus** [comment]
The local notification plugin has quiet a few issues, mainly with iOS10 at this time.
I suggest, adding the reminder to the calendar, which also could emit a notification.

**Drawback: probably not all users use their mobile calendar and it would be new to them**

There are a few issues with the requesting the privilege to write to the calendar. iOS cannot re-request the privilege and the user has to understand how the re-grant the right, if he has refused the app's request and changed his mind.

**The main issue is however, when to add the reminders**.

Proposal:
- Add reminder/calendar at the invitation accept time.
- No possibility to add/remove reminders later in the first implementation 
- Added only on the device where the user accepts the invitation

**Comment by ursmeier-mercatus** [comment]
Can we close this?

**Comment by xamplo** [comment]
Actually I tend to keep it open until the balloon notification on app icon level is working with ionic

**Comment by ursmeier-mercatus** [comment]
OK. I had the opinion that the calendar feature replaces the badge/balloon.
I will have a look into the badges then.

**Comment by xamplo** [comment]
is working now!!!
